In [1]:
values = [1,2,3,4,5]
print (values)
for i in range(len(values)):
  values[i] += 5
print (values)

[1, 2, 3, 4, 5]
[6, 7, 8, 9, 10]


In [2]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [4]:
import numpy as np

values = [1,2,3,4,5]
print (values)
values = np.array(values) + 5
print (values)

[1, 2, 3, 4, 5]
[ 6  7  8  9 10]


In [5]:
values = [1,2,3,4,5]
x = np.multiply(values, 5)
print (x)

[ 5 10 15 20 25]


In [7]:
a = [[1,2],[3,4]]
print (a)
b = [[5,6],[7,8]]
print (b)
print (a+b)

[[1, 2], [3, 4]]
[[5, 6], [7, 8]]
[[1, 2], [3, 4], [5, 6], [7, 8]]


In [9]:
a = np.array([[1,2],[3,4]])
print (a)
b = np.array([[5,6],[7,8]])
print (b)
print (a+b)

print (a.shape)
print (b.shape)
print ((a+b).shape)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
(2, 2)
(2, 2)
(2, 2)


In [0]:
a = np.array([[1,2,3,4],[5,6,7,8]])

In [11]:
a.shape

(2, 4)

In [12]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [13]:
b.shape

(4, 3)

In [14]:
c = np.matmul(a, b)
c

array([[ 70,  80,  90],
       [158, 184, 210]])

In [15]:
c.shape

(2, 3)

In [16]:
d = np.matmul(b,a)

ValueError: ignored

In [17]:
m = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
m.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])